version: "3.9" # Specify Docker Compose version
services:
  kab-transcribe:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_DATE: 2024-06-11
    pull_policy: build
    container_name: kab-transcribe-container
    restart: unless-stopped
    ports:
      - "3444:3444" # Map port 3000 in the container to 3000 on your machine
    volumes:
      - ./uploads:/app/uploads
      - ./cuts:/app/cuts
      - /app/node_modules #
