version: "3.9" # Specify Docker Compose version
services:
  kab-transcribe:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_DATE: 2024-08-10
    pull_policy: build
    container_name: kab-transcribe-container
    restart: unless-stopped
    ports:
      - "3445:3445"
    volumes:
      - ./uploads:/app/uploads
      - ./cuts:/app/cuts
      - /app/node_modules #
